### ISSUE TITLE
About issue with idp

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/askbot-openmooc#6]
Hi, this is a error:

![error](https://f.cloud.github.com/assets/428820/332616/e7fc2998-9c33-11e2-9af0-b2af06035041.png)

Please tell me something about that, because i tell it continues so many times and nothing happened

TNks

**Comment by satyaakam** [comment]
i do not understand any of the spanish i see on the image :P 

-Satya

**Comment by pitbulk** [comment]
@johnfelipe The Warning message is due you are sending a POST from an HTTPs view to a HTTP view.
Force those views to be served under HTTPs.

Also you could get other warnings due mix elements served under HTTP in an HTTPs connection.
In order to avoid this kind of message, search those elements and serve them under HTTPs too.

More info of the problems mix http/https content:
https://www.sslshopper.com/article-stop-the-page-contains-secure-and-nonsecure-items-warning.html

**Comment by johnfelipe** [comment]
Tnks again and sorry about support list

**Comment by satyaakam** [comment]
@johnfelipe you can join this group https://groups.google.com/group/openmooc and post your questions 

-Satya

**Comment by johnfelipe** [comment]
Hello its working only i have http://questions.xxx.com in local_setting and change that to https, and solved, but in https://questions.domain.com/germany-for-colombians/questions/ i take "ir al curso" and send me to http://questions.domain.com/course/germany-for-colombians/, why, tnks for all
